export {default as About} from './About'
// export {default as Contact} from  './Contacts'
// export {default as Events} from  './Events'
// export {default as Home} from './AdminHome'
// export {default as Products} from './Products'
// export {default as Error} from './Error'
export {default as MainMenu} from './NavMenu'
export {default as PageTemplate} from './PageTemplate'
export {default as AboutMenu} from './AboutMenu'
export {default as AdminInfo} from './AdminInfo'